Repository DuckDuckStudio/GitHub-Labels-Manager, pull requests merged in 2024-07, with the labels that each got.

#4 [pref] 优化代码以减少重复工作
  other-languages/en_US/glm-en_US.py
  程序脚本/glm.py
Labels: DEV-本地测试通过, 优化

#2 [docs] 更新winget获取方式以及如何查看帮助
  README.md
Labels: DEV-开发分支合并, DEV-本地测试通过, DEV-需要注意, 内部任务, 待发布, 文档

#8 更新winget支持版本文档
  README.md
Labels: DEV-开发分支合并, DEV-本地测试通过, 内部任务, 文档, 第三方

#10 [翻译] 翻译文档 version 1.2
  README.md
  other-languages/en_US/README.md
Labels: DEV-本地测试通过, DEV-需要注意, 内部任务, 名称, 处理中, 已有临时平替, 文档
